### ISSUE TITLE
newsletter button not working

### ISSUE THREAD

**Issue by fratzinger** [locokit/locokit#11]
Hi, 
author of [feathers-casl](https://github.com/fratzinger/feathers-casl) here 👋.
I saw that you're using `feathers-casl` which is pretty awesome! I'm curious what locokit will be like. The website looks promising. If I understand it right, it's a headless cms based on `vue` and `feathers.js`. I also thought about this approach. If you need help with `feathers-casl` please let me know!

I wanted to subscribe to your newsletter. Unfortunately the button `Yes, subscribe me to the newsletter.` in the mail is not clickable (mac monterey 12, chrome and safari). Sorry if it's the wrong place here.

**Comment by mdartic** [comment]
Nice to see you here @fratzinger :-)

Thanks for your report, we'll check that.

**Comment by fratzinger** [comment]
confirmed :)

**Comment by mdartic** [comment]
And to answer more precisely what locokit is, indeed, it's a vue + feathers app, trying to be a "nocode / lowcode" app, allowing users to create their app.

We use feathers-casl under the hood to check permissions dynamically, according the permission given or configured by the "administrator" user.

We are not up-to-date with your latest version, but we hope we'll soon upgrade your package to the latest one.

For the moment, as we released the code recently, we need to :muscle: the code and CI, as it breaks too often !

**Comment by fratzinger** [comment]
Nice, thanks for the clarification. I'm really happy to see others using a package of mine. Even if it's such a cool app like yours.

I'll be eagerly waiting for new updates on the newsletter.
Please make sure to let me know if you got any questions with `feathers-casl`.

**Comment by mdartic** [comment]
Yup, don't worry, I won't hesitate if we are blocked ;-)

We are stick to the `0.6.1-6`, and I hope we'll upgrade to `0.7.x` soon. As it's an important feature for security, we'll need to check our tests to see if there are any regression or misuse. The library is used against a meta model, we are really careful on this app side.

And, by the way, thanks a lot for your package allowing us to use casl directly in our feathers app (and that works too with feathers-objection). That's really really nice. (really !)

**Comment by fratzinger** [comment]
I use it with `feathers-sequelize` by myself and also store the permissions in the db for dynamic permissions per organization.

I've also built `feathers-trigger`: https://feathers-trigger.netlify.app/getting-started.html#about . Maybe that's interesting for a nocode app.

**Comment by mdartic** [comment]
Another interesting extension !

It could be nice for locokit too, as we manage already triggers for calling external hooks. But for today, we don't manage conditions, only the trigger (create / update / ...).

Nice !
