### ISSUE TITLE
[UserAdmin] Sort by default user by created date

### ISSUE THREAD

**Issue by Alketta** [locokit/locokit#136]

**Comment by mdartic** [comment]
Do you think it could be useful to allow user to sort on the field he want ?
Like the name, email, createdAt, verified, etc. ?

If so, I think we could open another issue for this feature.

**Comment by Alketta** [comment]
> Do you think it could be useful to allow user to sort on the field he want ? Like the name, email, createdAt, verified, etc. ?
> 
> If so, I think we could open another issue for this feature.

It is already the case.

**Comment by mdartic** [comment]
Wow... I need some refresh I think ;-)
