### ISSUE TITLE
[CSS] Impove var and override in scss file

### ISSUE THREAD

**Issue by Alketta** [locokit/locokit#171]
In many scss file, there are plenty of #… Maybe we can use a css var.

It is possible that some components do not correspond to the old version of LocoKit. We must locate and overload them correctly. Today, some variables are already noted (there is a comment `// Custom` next to them) but they have not been overloaded.

**Comment by mdartic** [comment]
To go further for the `next` version, do you think [this](https://tailwind.primevue.org/nuxt/) could help us ?

Using the `unstyled` PrimeVue components could help us define our colors ? 
Is it a "big" work ?

There is an example repo : https://github.com/primefaces/primevue-examples/tree/main/nuxt-unstyled-tailwind

**Comment by mdartic** [comment]
So after some exploration on side project (RODolPh, CaPeL PWA), the unstyled primevue version seems OK for LocoKit.

This work need to be done after primevue v4 is "unstyl-able".

**Comment by mdartic** [comment]
The new package `@locokit/vue-components` allows us to use PrimeVue directly in the client-side application.

We can close this issue, as we are autonomous regarding CSS vars, and only dependent of the way PrimeVue & Tailwind work together.
