### ISSUE TITLE
[i18n] Change root for locokit translations

### ISSUE THREAD

**Issue by mdartic** [locokit/locokit#268]
To be more adaptable for specific project translations,
and to avoid translation key pollution,
we need to move all locokit-specific translations in a dedicated key, `locokit`.

This would give us a i18n object like this : 

```js
{
  en: {
    locokit: { all actual translations ... },
    [project specific key]: { project specific translations }
  },
  fr: {
    locokit: { all actual translations ... },
    [project specific key]: { project specific translations }
  }
}
```

**Comment by Alketta** [comment]
> To be more adaptable for specific project translations, and to avoid translation key pollution, we need to move all locokit-specific translations in a dedicated key, `locokit`.
> 
> This would give us a i18n object like this :
> 
> ```js
> {
>   en: {
>     locokit: { all actual translations ... },
>     [project specific key]: { project specific translations }
>   },
>   fr: {
>     locokit: { all actual translations ... },
>     [project specific key]: { project specific translations }
>   }
> }
> ```

Why ? I don't understand the use and you don't use it in other projects that include the design system library.

**Comment by mdartic** [comment]
I use it for the capel project, this allows me to have "capel-specific" translations at the same time.

We have only one instance of `vue-i18n`, so I need to allow a mix of translations, as described in the issue, so it gives me : 

```
{
  en: { 
    locokit: ...
    capel: ...
  },
  ...
}
```

Better ?

**Comment by Alketta** [comment]
> I use it for the capel project, this allows me to have "capel-specific" translations at the same time.
> 
> We have only one instance of `vue-i18n`, so I need to allow a mix of translations, as described in the issue, so it gives me :
> 
> ```
> {
>   en: { 
>     locokit: ...
>     capel: ...
>   },
>   ...
> }
> ```
> 
> Better ?

No, but after discuss I understand your thinking.

Your proposition concerned an improvement for custom project : to avoid a possibly conflict between translation key in LocoKit and custom project, i.e. to have an identical key in both projects.

Maybe we can prefix only custom project? As you want

**Comment by mdartic** [comment]
I think it's better to separate each translation with a specific key, `locokit` for all related to `locokit`.
With this strategy, I think we'll be sure to avoid key conflicts in the future.
