### ISSUE TITLE
[View] When editing a view show only the fields of the current view

### ISSUE THREAD

**Issue by bruhnild** [locokit/locokit#32]

**Comment by mdartic** [comment]
This could be useful for restricting field displayed when a table has a consequent number of fields.

We need to explain it to the user, and allow him to choose to display all table fields, and select "by default" the view fields.

**Comment by Alketta** [comment]
> This could be useful for restricting field displayed when a table has a consequent number of fields.
> 
> We need to explain it to the user, and allow him to choose to display all table fields, and select "by default" the view fields.

I don't think we need to have an option to display fields from the view only or all fields in the table. I don't see the need for a user to have this feature. Can you specify, please? 

For now, I have allow to display the fields in the detail view in the same order as those in the table and only those in the current view.

As an alternative to your idea, I think it's better to "force" the creation of a view with all the columns (when you create a view) and provide a system to either warn the user that there are new columns or add them automatically.

And to go further, I wonder if this automatically created view should not be available in the CMS as a selected view. What do you think ?
