### ISSUE TITLE
[Pages] Always display the pages in the same order

### ISSUE THREAD

**Issue by bruhnild** [locokit/locokit#78]
The order defined by the SUPERADMIN user

![image](https://user-images.githubusercontent.com/26433045/160839808-860e1f12-c949-47d7-8f55-86e4af6b7ef8.png)

The rendered order when logged as a different user

![image](https://user-images.githubusercontent.com/26433045/160840089-4de38225-66f8-4e91-81f7-fb742955283e.png)

**Comment by mdartic** [comment]
I suspect we don't retrieve pages in the same order than in the workspace admin section.

Need to check that.
