### ISSUE TITLE
[User/Group Management] Enhance UI for group and user management

### ISSUE THREAD

**Issue by mdartic** [locokit/locokit#92]
We need to improve these screens.

Actually, groups are displayed in a left column, but we can't search in it.

For users, all users are displayed in a table, but we can filter on it.

We need to think about how we want to present the data to the end user, and allow him to filter on it.

I like the layout with two columns, one for the group's listing, the other for the group's detail.
But we have to add a way to filter the list, like it's done on the user table.

**Comment by mdartic** [comment]
I think this issue can now be part of v1.
@Alketta don't you think ?

**Comment by Alketta** [comment]
> I think this issue can now be part of v1. @Alketta don't you think ?

Yes, let's do it!

**Comment by mdartic** [comment]
I think this is related to #208 and #217 

I consider this is done and already in the v1-next.

WDYT @Alketta ?
